sudo: required
services:
  - docker

before_install:
  - docker build -t newcipher/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true newcipher/client-test yarn test

after_success:
  - docker build -t newcipher/multi-client ./client
  - docker build -t newcipher/multi-nginx ./nginx
  - docker build -t newcipher/multi-server ./server
  - docker build -t newcipher/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push newcipher/multi-client
  - docker push newcipher/multi-nginx
  - docker push newcipher/multi-server
  - docker push newcipher/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-306476627547
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
